export const defaultTags = [
  "T-shirts",
  "Blouses",
  "Button-ups",
  "Tank tops",
  "Sweaters",
  "Hoodies",
  "Sweatshirts",
  "Crop tops",
  "Long-sleeves",
  "Jeans",
  "Trousers",
  "Shorts",
  "Skirts",
  "Leggings",
  "Chinos",
  "Capris",
  "Casual dresses",
  "Formal gowns",
  "Maxi dresses",
  "Midi dresses",
  "Sundresses",
  "Cocktail dresses",
  "Shift dresses",
  "Wrap dresses",
  "Coats",
  "Jackets",
  "Blazers",
  "Parkas",
  "Trench coats",
  "Windbreakers",
  "Cardigans",
  "Sports bras",
  "Yoga pants",
  "Athletic shorts",
  "Tracksuits",
  "Gym T-shirts",
  "Compression wear",
  "Underwear",
  "Bras",
  "Camisoles",
  "Shapewear",
  "Sleepwear",
  "Sneakers",
  "Sandals",
  "Boots",
  "Loafers",
  "Heels",
  "Flats",
  "Clogs",
  "Scarves",
  "Hats",
  "Belts",
  "Gloves",
  "Jewelry",
  "Sunglasses",
  "Swimwear",
  "Loungewear",
  "Workwear",
  "Costumes",
]
